  app:
    image: nickzorych/php:IntITA
    user: ${USER_ID}:${USER_GID}
    container_name: "IntITA_app"
    volumes:
      - ./:/app
    links:
      - db
      - redis
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  nginx:
    container_name: "IntITA_nginx"
    image: nginx:1.12-alpine
    user: ${USER_ID}:${USER_GID}
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./:/app
      - ./docker_conf/nginx/intita.conf:/etc/nginx/conf.d/vhost.conf
    links:
      - app

  mailcatcher:
      container_name: "IntITA_mailcatcher"
      image: schickling/mailcatcher:latest
      ports:
        - 1080:1080

  db:
    image: mysql:5.7
    user: ${USER_ID}:${USER_GID}
    container_name: "IntITA_db"
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
      - ./docker_conf/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWD}
  redis:
    image: redis:latest

  bower:
       container_name: "IntITA_bower"
       user: ${USER_ID}:${USER_GID}
       image: digitallyseamless/nodejs-bower-grunt:latest
       volumes:
        - ./angular:/data
       command: bower install